apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: applications
  namespace: openshift-gitops
spec:
  destination:
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    path: applications
    repoURL: 'https://github.com/Sarah123445/openshift-post-config.git'
    targetRevision: main
  syncPolicy:
    automated: {}