apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-logging
  namespace: openshift-gitops
spec:
  destination:
    server: 'https://kubernetes.default.svc'
  ignoreDifferences:
    - group: integreatly.org
      jsonPointers:
        - /spec/datasources/0/secureJsonData/httpHeaderValue1
      kind: GrafanaDataSource
  project: default
  source:
    path: cluster-logging/overlay/dev
    repoURL: 'https://github.com/Sarah123445/openshift-post-config.git'
    targetRevision: reduced-demo
  syncPolicy:
    automated: {}
