apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tenants
  namespace: openshift-gitops
spec:
  destination:
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    path: tenants/overlay/dev
    repoURL: 'https://github.com/Sarah123445/openshift-post-config.git'
    targetRevision: reduced-demo
  syncPolicy:
    automated: {}