kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: openshift-gitops-openshift-gitops-argocd-application-controller-additonal
  labels:
    app.kubernetes.io/instance: openshift-gitops
rules:
  - verbs:
      - '*'
    apiGroups:
      - ""
    resources:
      - services  
  - verbs:
      - '*'
    apiGroups:
      - "apps.openshift.io"
    resources:
      - deploymentconfigs
  - verbs:
      - '*'
    apiGroups:
      - "apps.3scale.net"
    resources:
      - apimanagers 
  - verbs:
      - '*'
    apiGroups:
      - "keycloak.org"
    resources:
      - keycloaks  
      - keycloakclients
  - verbs:
      - '*'
    apiGroups:
      - "route.openshift.io"
    resources:
      - routes
  - verbs:
      - '*'
    apiGroups:
      - "logging.openshift.io"
    resources:
      - elasticsearches
      - clusterloggings
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: gitops-additonal-rbac
  labels:
    app.kubernetes.io/instance: openshift-gitops
subjects:
  - kind: ServiceAccount
    name: openshift-gitops-argocd-application-controller
    namespace: openshift-gitops
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: openshift-gitops-openshift-gitops-argocd-application-controller-additonal
