apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  name: apicast-production
  namespace: 3scale
spec:
  replicas: 1
  selector:
    deploymentconfig: apicast-production
  strategy:
    type: Rolling
  template:
    metadata:
      labels:
        deploymentconfig: apicast-production
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: '9421'
    spec:
      containers:
      - env:
        # - name: THREESCALE_PORTAL_ENDPOINT
          # value: abc-123
          # valueFrom:
            # secretKeyRef:
              # name: apicast-configuration-url-secret
              # key: password
        # - name: THREESCALE_CONFIG_FILE
          # value: 
        - name: THREESCALE_DEPLOYMENT_ENV
          value: production
        - name: APICAST_CONFIGURATION_LOADER
          value: lazy
        - name: APICAST_PATH_ROUTING
          value: "False"
        - name: APICAST_RESPONSE_CODES
          value: "False"
        - name: APICAST_MANAGEMENT_API
          value: status
        - name: OPENSSL_VERIFY
          value: "False"
        name: apicast-production
        livenessProbe:
          httpGet:
            path: /status/live
            port: 8090
            scheme: HTTP
          initialDelaySeconds: 30
          timeoutSeconds: 3
          failureThreshold: 3
          periodSeconds: 10
          successThreshold: 1
        readinessProbe:
          httpGet:
            path: /status/ready
            port: 8090
            scheme: HTTP
          initialDelaySeconds: 60
          timeoutSeconds: 3
          failureThreshold: 3
          periodSeconds: 10
          successThreshold: 1
        ports:
        - name: proxy
          containerPort: 8080
          protocol: TCP
        - name: management
          containerPort: 8090
          protocol: TCP
        - name: metrics
          containerPort: 9421
          protocol: TCP
        resources:
          limits:
              cpu: '1'
              memory: 128Mi
          requests:
              cpu: 500m
              memory: 64Mi
        terminationMessagePath: /dev/termination-log	
        terminationMessagePolicy: File
  triggers:
  - type: ConfigChange
---
kind: Service
apiVersion: v1
metadata:
  name: apicast-production-svc
  namespace: 3scale
  labels:
    app: 3scale-api-management
spec:
  ports:
    - name: gateway
      protocol: TCP
      port: 8080
      targetPort: 8080
    - name: management
      protocol: TCP
      port: 8090
      targetPort: 8090
    - name: https
      protocol: TCP
      port: 8443
      targetPort: 8443
  selector:
    deploymentconfig: apicast-production
---
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: apicast-production
  namespace: 3scale
spec:
  to:
    kind: Service
    name: apicast-production
    weight: 100
  port:
    targetPort: https
  tls:
    termination: passthrough
  wildcardPolicy: None