apiVersion: batch/v1
kind: Job
metadata:
  name: cert-install
  namespace: 3scale
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
      spec:
        containers:
          - image: registry.redhat.io/openshift4/ose-cli:v4.8
            command:
              - /bin/bash
              - -c
              - |
                set -e
                echo "Storing zync pod name as POD environment variable"
                POD=`oc get ep zync -o jsonpath={.subsets[0].addresses[0].targetRef.name}`
                echo "Extracting zync pod certs as output to txt"
                oc exec ${POD} cat /etc/pki/tls/cert.pem >> zync.pem
                echo "Extract custom certs from config map"
                oc get configmap custom-cert -o jsonpath={.data.custom-cert} >> zync.pem
                echo "Create configmap on cluster containing zync.pem"
                oc create configmap zync-ca-bundle --from-file=zync.pem
                echo "Set volume for zync pod"
                oc set volume dc/zync --add --name=zync-ca-bundle --mount-path /etc/pki/tls/zync/zync.pem --sub-path zync.pem --source='{"configMap":{"name":"zync-ca-bundle","items":[{"key":"zync.pem","path":"zync.pem"}]}}'
                echo "Set SSL_CERT_FILE variable against Zync Pod"
                oc set env dc/zync SSL_CERT_FILE=/etc/pki/tls/zync/zync.pem
            imagePullPolicy: Always
            name: cert-install
        restartPolicy: "OnFailure"