apiVersion: keycloak.org/v1alpha1
kind: KeycloakClient
metadata:
  name: dev-client
  namespace: keycloak
  labels:
    app: sso
spec:
  client:
    clientAuthenticatorType: client-secret
    clientId: dev-client
    directAccessGrantsEnabled: true
    secret: client-secret
  realmSelector:
    matchLabels:
      app: sso