apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: 3scale-operator
  namespace: 3scale
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  targetNamespaces:
   - 3scale