apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: keycloak-operator
  namespace: keycloak
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  targetNamespaces:
   - keycloak