kind: Secret
apiVersion: v1
metadata:
  name: alertmanager-main
  namespace: openshift-monitoring
  labels:
    alertmanager: main
    app.kubernetes.io/component: alert-router
    app.kubernetes.io/name: alertmanager
    app.kubernetes.io/part-of: openshift-monitoring
    app.kubernetes.io/version: 0.21.0
data:
  alertmanager.yaml: >-
    Z2xvYmFsOgogIHJlc29sdmVfdGltZW91dDogNW0KaW5oaWJpdF9ydWxlczoKICAtIGVxdWFsOgogICAgICAtIG5hbWVzcGFjZQogICAgICAtIGFsZXJ0bmFtZQogICAgc291cmNlX21hdGNoOgogICAgICBzZXZlcml0eTogY3JpdGljYWwKICAgIHRhcmdldF9tYXRjaF9yZToKICAgICAgc2V2ZXJpdHk6IHdhcm5pbmd8aW5mbwogIC0gZXF1YWw6CiAgICAgIC0gbmFtZXNwYWNlCiAgICAgIC0gYWxlcnRuYW1lCiAgICBzb3VyY2VfbWF0Y2g6CiAgICAgIHNldmVyaXR5OiB3YXJuaW5nCiAgICB0YXJnZXRfbWF0Y2hfcmU6CiAgICAgIHNldmVyaXR5OiBpbmZvCnJlY2VpdmVyczoKICAtIG5hbWU6IERlZmF1bHQKICAtIG5hbWU6IFdhdGNoZG9nCiAgLSBuYW1lOiBDcml0aWNhbAogIC0gbmFtZTogcGFnZXJkdXR5X2dlbmVyYWwKICAgIHNsYWNrX2NvbmZpZ3M6CiAgICAgIC0gYXBpX3VybDogaHR0cHM6Ly9ob29rcy5zbGFjay5jb20vc2VydmljZXMvVEVIQTY4U1ZDL0IwMkpLVTJQVkFNL1VRU0xLNVphNnRoUGpNbExWSFNZRXN2UwogICAgICAgIGNoYW5uZWw6ICcjb2NwLWFsZXJ0cycKcm91dGU6CiAgZ3JvdXBfYnk6CiAgICAtIG5hbWVzcGFjZQogIGdyb3VwX2ludGVydmFsOiA1bQogIGdyb3VwX3dhaXQ6IDMwcwogIHJlY2VpdmVyOiBEZWZhdWx0CiAgcmVwZWF0X2ludGVydmFsOiAxMmgKICByb3V0ZXM6CiAgICAtIG1hdGNoOgogICAgICAgIGFsZXJ0bmFtZTogV2F0Y2hkb2cKICAgICAgcmVjZWl2ZXI6IFdhdGNoZG9nCiAgICAtIG1hdGNoOgogICAgICAgIHNldmVyaXR5OiBjcml0aWNhbAogICAgICByZWNlaXZlcjogQ3JpdGljYWwKICAgIC0gbWF0Y2g6CiAgICAgICAgc2V2ZXJpdHk6IHBhZ2VyZHV0eQogICAgICByZWNlaXZlcjogcGFnZXJkdXR5X2dlbmVyYWwK
type: Opaque
