apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Operator files need installing before operatorAPI operations are performed
resources:
- instance/apicast.yaml
- instance/api-manager.yaml
- instance/custom-cert.yaml
- instance/zync-que.yaml
- instance/zync-post-job.yaml
- instance/rbac.yaml
- operator/namespace.yaml
- operator/operator-subscription.yaml
- operator/operator-group.yaml
