apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- operator/namespace.yaml
- operator/operator-subscription.yaml
- operator/operator-group.yaml
- instance/apicast.yaml
- instance/api-manager.yaml
- instance/zync-ca-bundle.yaml
- instance/zync-que.yaml