apiVersion: logging.openshift.io/v1
kind: ClusterLogForwarder
metadata:
  name: instance
  namespace: openshift-logging
spec:
  outputDefaults:
    elasticsearch:
      structuredTypeKey: kubernetes.labels.logFormat 
      structuredTypeName: nologformat
  pipelines:
    - inputRefs:
        - application
        - infrastructure
        - audit
      name: enable-default-log-store
      outputRefs:
        - default
    - inputRefs:
        - application
      name: json-parsing
      outputRefs:
        - default
      parse: json