apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: springboot-monitor
  namespace: demo-namespace
  labels:
    app.kubernetes.io/instance: metrics-demo
    k8s-app: prometheus-app-monitor
    prometheus: user-workloads
spec:
  endpoints:
    - interval: 30s
      path: /actuator/prometheus
      port: http
      scheme: http
  namespaceSelector:
    any: true
  selector:
    matchLabels:
      prometheus: user-workloads