apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: namespace-configuration-operator
  namespace: namespace-configuration-operator
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec: {}