apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- operator/namespace.yaml
- operator/operator-subscription.yaml
- operator/operator-group.yaml
- instance/jenkins.yaml
- instance/jenkins-sa-rbac.yaml